### ISSUE TITLE
Apply chat filter to usernames

### ISSUE THREAD

**Issue by dschwartz783** [MattWAnderson/PocketMiners#10]
I think it would make a whole lot of sense to disallow words which cannot be used in chat, to be used in usernames. We may want to be a bit more conservative with the list though, and make sure we use proper regex, to avoid matching names that aren't problems. A lot of kicks staff have to deal with should be fairly easy to automate that way.

**Comment by MattWAnderson** [comment]
We already do this with the user name Steve with a custom message to change name. Please provide a list of names in array format and I can add to the current code.

**Comment by dschwartz783** [comment]
I was thinking about something relying on the preg_match (a somewhat unfortunately named function) for matching based on regular expressions, looking for certain words. A list-based approach probably isn't ideal for this sort of thing, except for the most common problematic name Steve.

**Comment by MattWAnderson** [comment]
Welcome to code something and we can have a look. I was thinking an array of names for checking on join. Right now I am just hunting for Steve

	if (strtolower($player->getName()) == strtolower("Steve")) {
			$event->setCancelled(true);
			$player->close("", "§3Please change your name from Steve in OPTIONS and try again!!");
		}

**Comment by dschwartz783** [comment]
I could probably throw something simple together, sure.

**Comment by dschwartz783** [comment]
The plugin can be downloaded here. Simply add words to the list of words banned for usernames in the JSON file, but keep in mind that this should not be used with words which aren't really a problem, like Steve, or I won't be able to join... This will block anyone trying to join the server with a few expletives that I thought of off the top of my head, appearing anywhere in their username.
https://www.dropbox.com/s/onlgi5bvnulrhm9/PMNameFilter.zip?dl=1
