### ISSUE TITLE
Player killing themselves with arrows causing spam on server of death message 

### ISSUE THREAD

**Issue by JasonTheChef** [MattWAnderson/PocketMiners#12]
- When a player kills themself the Death message "Player has been shot by an arrow by player" is repeated spamming the server until a reboot could be related to the Money plugin

**Comment by MattWAnderson** [comment]
Added code where if the killer is the victim it will not run any money calculations. Will have to test.

**Comment by MattWAnderson** [comment]
Added some code to remove this. Should be fixed.
