### ISSUE TITLE
commands idea

### ISSUE THREAD

**Issue by jes282010** [MattWAnderson/PocketMiners#14]
/list staff to see the current staff online for the servers

**Comment by MattWAnderson** [comment]
This has been applied to the server, I cannot get the server software to work nicely with this though oddly it doesn't like using foreach when listing OPs May be a server bug.

**Comment by dschwartz783** [comment]
What's the problem with it? I just wrote a small plugin that's able to list ops. Seems to work.

**Comment by dschwartz783** [comment]
Invited you to the plugin I threw together. Seems to work on my server at least.
https://github.com/dschwartz783/PMOpList/invitations

**Comment by MattWAnderson** [comment]
This is done with NotifyAdmin for end users now.
