### ISSUE TITLE
Discord communication ideas

### ISSUE THREAD

**Issue by jes282010** [MattWAnderson/PocketMiners#15]
I think the build Team or teams. Need their own channel cause currently it's a mess with mailey and goalie them trying to talk about the build and everyone getting involved also it would need a password so not everyone can be there just the builders for the specified projects if we were to do it that way :) lets make this stuff happen it should be that hard with discord i know you can do it with ts for the passwords can we do it with discord? they need that communication to help with the build so everyone can get on the same page and have the chat in enabled also so if the builders are on the different time zones there won't be no issues for them to catch up or also place all the builders on the same time zones to those builds so theres no way there's not all there at the same time there's just an idea

**Comment by MattWAnderson** [comment]
We can make a voice channel, no problem there. No text though they have a sb area for that.
