### ISSUE TITLE
Slow furnace glitch

### ISSUE THREAD

**Issue by molemanx0504** [MattWAnderson/PocketMiners#16]
Furnaces are taking a long time to burn anything. This issue is one that has returned over and over and is annoying players

**Comment by dschwartz783** [comment]
@MattWAnderson Are one of the furnace events being used for anything?

**Comment by MattWAnderson** [comment]
Nope, currently that is pure server.

**Comment by dschwartz783** [comment]
Feel free to open an issue on https://github.com/iTXTech/Genisys/issues
This issue is better off in their capable hands.
