### ISSUE TITLE
Social media tags

### ISSUE THREAD

**Issue by MMLighting** [MattWAnderson/PocketMiners#17]
Can we look at adding our twitter, youtube and instagram link buttons on the site?

**Comment by dschwartz783** [comment]
Might also make sense to add a /social command in-game, although less useful because we won't be able to give them links.

**Comment by MMLighting** [comment]
Can just add that into qr david



On Tue, Jul 26, 2016 at 8:48 AM +0100, "David Schwartz" <notifications@github.com<mailto:notifications@github.com>> wrote:


Might also make sense to add a /social command in-game, although less useful because we won't be able to give them links.

-

**Comment by dschwartz783** [comment]
True. @Legoburner73 Another QR idea

**Comment by Legoburner73** [comment]
Will get it sorted.

**Comment by MMLighting** [comment]
You can find the social media links on the welcome to pm section of the forums

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Jul 26, 2016 at 9:00 AM +0100, "Legoburner73" <notifications@github.com<mailto:notifications@github.com>> wrote:


Will get it sorted.

-

**Comment by MattWAnderson** [comment]
Assigned to Ender.

**Comment by enderjulie** [comment]
Yes it's done!!!
