### ISSUE TITLE
Add /TpaBlock for staff and players 

### ISSUE THREAD

**Issue by JasonTheChef** [MattWAnderson/PocketMiners#19]
Since /ignore is going to be disabled for staff members I think staff should be able to block tpas from a user and also what if the user only wants to not accept tpas from the user but wants to still see there chat /tpablock would fix this :)

**Comment by dschwartz783** [comment]
I'm doing a bit of a refactor at the moment, but when I'm done I'll work on this. :)

**Comment by dschwartz783** [comment]
I have implemented /blocktpa /unblocktpa and /blocktpalist. Waiting on someone with file access to upload. @MattWAnderson

**Comment by dschwartz783** [comment]
It has been uploaded. Cheers!
