### ISSUE TITLE
Suggested command 

### ISSUE THREAD

**Issue by molemanx0504** [MattWAnderson/PocketMiners#22]
I was thinking of a command that could find if one user was online or offline. Sometimes when around 100 users are on at once you can't see everyone in /list. Maybe /list find (user)?

**Comment by Damcp04** [comment]
Would be great if we could use /list with filters. For example: /filterlist (rank here) and only certain players with certain rank will be shown. Or typing /list will show 25 players, typing /list 2 the next 25 and so on. And the /list find (user) can be useful too.

**Comment by Pawsipoo** [comment]
Add /f allie <Faction Name> So factions can team up and can share a base. And not kill eachother.

**Comment by Damcp04** [comment]
ally* I guess

2016-08-13 20:56 GMT-06:00 Pawsipoo <notifications@github.com>:

**Comment by MattWAnderson** [comment]
Servers are split now, should be a null issue.
