### ISSUE TITLE
App

### ISSUE THREAD

**Issue by Damcp04** [MattWAnderson/PocketMiners#23]
I was thinking of a great idea for new players. We could have a PocketMiners app as we had a MinePocket one before. Could be great if you could access to the forums through the app and for example the first time opened the app it can show a menu which shows the logo and two buttons below "Sign Up!" and "Log In" and when tapping Sign Up! it redirects you to the Sign Up web we have then, it sends you to a tutorial about how to join the servers and you choose to skip or keep watching it. The Log In one sends it to login web and when logged in shows tutorial (how to join servers) too and you choose too skip or not. And then the rest is just the website.

**Comment by molemanx0504** [comment]
Would the tutorials be picture based or Video?

**Comment by Damcp04** [comment]
A slideshow could be great.

**Comment by dschwartz783** [comment]
I am designing an app for PocketMiners which does some of this, but the functionality is still limited because I haven't been granted access to much yet. It's a lot more than just a website though, although it does draw a lot of its data from there.

**Comment by MattWAnderson** [comment]
Please let me know what further access is needed. I will use the simple webview template again for Android.

**Comment by Damcp04** [comment]
Uh it would be really great that it started in a login or signup page as said before but not as a website, like facebook or twitter app login start page i mean but i dunno if that is possible and all after signing in or login in is just the website in the app

**Comment by dschwartz783** [comment]
I only have access to authenticate and getUser at the moment. None of the other actions seem to work.

**Comment by dschwartz783** [comment]
@MattWAnderson Wondering if you're alive. Still working on this app, can't improve it much with only authenticate and getUser.

**Comment by MattWAnderson** [comment]
What added access do you require?

**Comment by dschwartz783** [comment]
Messaging-related stuff. Conversation actions I believe they're called. I'm working on a very easy way for our players to do Genisys plugin development now, almost complete. Won't have very much time for the app now that the semester's starting, so I'll have to release it as-is.

**Comment by dschwartz783** [comment]
After being treated rudely by Ender, I have left PocketMiners, and I am no longer working on the app, and I have deleted it from my computer and iOS devices. It is no longer a concern of mine. Deal with her, or don't. Don't care.

**Comment by MattWAnderson** [comment]
See comments.
