### ISSUE TITLE
Command Requests by a Few Members

### ISSUE THREAD

**Issue by JasonTheChef** [MattWAnderson/PocketMiners#3]
- Add /ignore to ignore a player who is bothering you
- Add /block to block a person from Tpa requesting you
- Add /Friend to allow friends to teleport to you using /TpFriend

**Comment by Luckysocks** [comment]
Good ideas!

**Comment by Legoburner73** [comment]
All of those commands are cool. I might try one of them in PMCommands.

**Comment by Damcp04** [comment]
You could also try adding /vanish <player name> to disappear players that bother you but only applies to the player who executes the command, except in PvP areas.

**Comment by dschwartz783** [comment]
I have created an ignore list plugin for you PocketMiners. It has 3 commands: /ignore /unignore and /ignorelist. I invited you, Matt: https://github.com/dschwartz783/PMSocial/invitations

**Comment by dschwartz783** [comment]
I have added /tpa and /tpahere blocking to the plugin, as a part of the /ignore functionality. Seemed to make sense to me.

**Comment by dschwartz783** [comment]
I have added a friend list, and integrated it with the ignore list functionality. Once hosty pushes the changes, all the requested commands should be working.

**Comment by dschwartz783** [comment]
Addon uploaded. Feel free to try it out!
