### ISSUE TITLE
/tpahere saying "tent a request" and the qr list is missing bemod 

### ISSUE THREAD

**Issue by molemanx0504** [MattWAnderson/PocketMiners#4]
/Qr list may be missing other commands.

**Comment by MattWAnderson** [comment]
@legoburner73

**Comment by Legoburner73** [comment]
Will fix this when I get back on the computer. The reason why it's missing some is because I had it only list main ones. Will make a full list similar to /help

**Comment by MattWAnderson** [comment]
"Tent a request" has been fixed. Will leave this open and assign to lego.

**Comment by Legoburner73** [comment]
Turns out there was no /qr list. Will add it today :)
