### ISSUE TITLE
Commands that dont work (OP Commands)

### ISSUE THREAD

**Issue by JasonTheChef** [MattWAnderson/PocketMiners#40]
This issue is caused by how Sammy Ops staff as when I deop myself then reop myself I gain all the commands that I'm supposed to have back. 

Commands: /kill 
/kick 
/tp 
/list

**Comment by WCMattAnderson** [comment]
Should be fixed now.

**Comment by MattWAnderson** [comment]
Fixed?

**Comment by JasonTheChef** [comment]
Fixed
