### ISSUE TITLE
EliteV+ Players can not run any command

### ISSUE THREAD

**Issue by JasonTheChef** [MattWAnderson/PocketMiners#41]
Any user who has Elitev+ Can not run any commands; this doesn't effect staff members (Mod and up)
Error shown: Unknown command (this is shown for commands a user can't run)

**Comment by WCMattAnderson** [comment]
Please test now.

**Comment by MattWAnderson** [comment]
Should now be fixed.

**Comment by JasonTheChef** [comment]
It is fixed
