### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by Damcp04** [MattWAnderson/PocketMiners#5]
Actually, we should get back to use Economy plugin and implement some of our own ideas, like a Jackpot. And also to get money we can add jobs to make it easier to get money and add bounties back again! Those were really good.

**Comment by MattWAnderson** [comment]
Please detail further desired features to be added. Cash system is still in the game.

**Comment by Mufina** [comment]
We should also have a casino ;) For those Bets

**Comment by Damcp04** [comment]
**Bounty**: Sets a reward (PM Cash) on someone, and when that player is killed, the set PM Cash amount by the player who set the bounty, will be paid to the player who killed the player the bonty was set to.

 For example:
 /setbounty (Player that bounty will set to) (Amount of money set). 

And if I do for example: /setbounty SpongeHost 1000 it will say:

 **Damcp04** has set a bounty on **SpongeHost**! Kill **SpongeHost** to get your reward of **$1000 PM Cash**! This bounty expires in **24 hours**!

**Comment by TashaTNT** [comment]
I also want to share an idea on this topic :) can I?

**Comment by Damcp04** [comment]
Yes you can

**Comment by Damcp04** [comment]
**Jobs**: There is a list of jobs.

woodcutter
miner

woodcutter- type ***/jobs join woodcutter*** to join to the job woodcutter and it will display:  

You have joined to the job **Wood Cutter**! Cut **Wood** (not Wooden Planks) to earn (amount of PM Cash) for every block of **Wood** you cut!

miner- type ***/jobs join miner*** to join the job miner and it will display:
 You have joined to the job **Miner**! Mine **Stone** or **Minerals** to earn (amount of PM Cash) for every block of **Stone** you mine!

/jobs will display

Available jobs: miner and treecutter (To join a job type /jobs join (job)

**Comment by MMLighting** [comment]
Can we look at tying pmbucks back into the site as was very useful to see momey handling.

**Comment by MattWAnderson** [comment]
I removed it as admins were giving out money.

**Comment by jes282010** [comment]
You can't #blamejes Matt when you get chance get on the pvp server thanks

**Comment by Damcp04** [comment]
If we add PM Cash it is better that we don't add the amount directly in the username because it uses many space in chat, or just show it to you.

**Comment by Damcp04** [comment]
I would like to take any MCPE coding courses so I just don't give ideas and give all the work to you. Do you recommend me any page or is there any coding language I have to know? PHP, Java, etc? Thanks.

**Comment by Mufina** [comment]
Isn't there already money in the game?? Or am I going crazy?

**Comment by MattWAnderson** [comment]
Closing. Not enough info. Please develop a plan and reopen.

**Comment by Damcp04** [comment]
https://pocketminers.com/threads/kits-benefits-of-elitev-etc.5274/#post-65792 here I hrought back the jobs idea involving the new server leveling system
