### ISSUE TITLE
Bringing Colors Back 

### ISSUE THREAD

**Issue by TashaTNT** [MattWAnderson/PocketMiners#7]
So I've Been Thinking Of Bringing Colors back on pm servers For the players Who have ranks Like Mvp, Mvp+, Etc. Alots Of People wants that back because sometimes when there are so many peoples online We aren't able to see what they are saying properly so I am just suggesting that if it is possible can we bring it back? Thank you for reading :)

Regards,
TashaTNT

**Comment by TashaTNT** [comment]
I am Talking about color for chat :)

**Comment by Damcp04** [comment]
That is great. Hosting, maybe we can add a perk that EliteV+ can use the color they want with a command like /textcolor red/blue/green/yellow etc..

**Comment by TashaTNT** [comment]
That sounds Awesome

**Comment by MattWAnderson** [comment]
Gold color added for EliteV+ members.
